### ISSUE TITLE
Friend was asking me about this theme.

### ISSUE THREAD

**Issue by L-m-b** [Chloe-ko/Discord-Stuff#1]
A friend of mine from the betterdiscord server was contacting me due to this theme being broken, and i spent an hour fixing it and got it working as i'd assumed it should be, Feel free to update the theme with this fixed file. 
[FIXED_minifiedMemberlist.theme.zip](https://github.com/Chloesviel/Discord-Stuff/files/2785452/FIXED_minifiedMemberlist.theme.zip)
BTW github won't let me upload the raw css file, so i had to put it in a zip folder.

**Comment by Chloe-ko** [comment]
Oh, damn. I'm so sorry for this late reply; I'm not used to people _actually using_ anything I write, so I never bothered to check this git repo (Because I also don't use GitHub a lot generally).
I also didn't know it was broken, as it works fine for me.
I tried your code and it actually re-introduces a bug I just fixed in a commit some minutes ago, with member lists being wrongly positioned. But that's fair as this code was written in January and that bug was introduced by Discord changes very recently.
But a quick question, if you're still up for helping. For me, personally, the code as it currently is in the repo works perfectly fine; It works even perfectly fine after I recently did a complete windows reinstall, so I don't think it just magically worked for me personally.
If you use the code in the repo right now, does it work or is it still broken?
If it still doesn't work, I'll take the liberty of using your reworked code and just adjusting it enough to fix that other bug I mentioned.

**Comment by L-m-b** [comment]
i believe they made a change which un-broke the original code
may have been one of the short lived updates that discord introduces very often, regardless it should be fine.

**Comment by Chloe-ko** [comment]
So the original code as-is works fine now?

**Comment by L-m-b** [comment]
It indeed works fine. the fix i made for it was just so it minimized properly, disregarding the animations and etc.
