### ISSUE TITLE
Theme not working for the new BetterDiscord v1.0

### ISSUE THREAD

**Issue by Kronweber** [Chloe-ko/Discord-Stuff#7]
the title's self explainatory ig

**Comment by Chloe-ko** [comment]
Ya I noticed it just now, will be fixed soon

**Comment by Chloe-ko** [comment]
Hey, it should be fixed and work with the new BetterDiscord again now, can anyone confirm this?

**Comment by dexman545** [comment]
Doesn't seem to be working on my end, and no changes were pushed to the repo recently either it seems.

**Comment by Chloe-ko** [comment]
Ah, right, I did forget to push the changes.
That shouldn't matter for functionality, though. The current .theme.css file pulls the actual css for the theme from the web.
Specifically, from [here](https://cfcdn.nyu.moe/minifiedMemberlist.source.css).
Are you using the latest .theme.css file which has `@import url('https://cfcdn.nyu.moe/minifiedMemberlist.source.css');` as first non-comment line?

**Comment by dexman545** [comment]
Mine has `@import url('https://chloe-ko.github.io/Discord-Stuff/minifiedMemberlist/minifiedMemberlist.source.css');` 
It's working now, I guess I should switch over to the nyu.moe one as well.

Thanks for fixing it!

**Comment by Chloe-ko** [comment]
Yeah, that was a previous one I used for a bit. The issue with it was that it quite quickly got blocked due to too many requests.
There are options to cache GitHub hosted files, but those all had some restriction that wouldn't quite work for updates if something breaks.. Like this time around. As those kind of options were meant for never-changing files.
So I'm just hosting it on a server I rented with caching from CloudFlare.

Either way, glad to hear it's working now!
